version: "3"
services:
  backend-aspnet:
    image: samarkinivan/messenger-server:latest
    container_name: messenger-server
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_HOST: database-mssql
    ports:
      - "8080:8080"
    depends_on:
      - database-mssql

  database-mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: messenger-database
    user: root
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: SecretPassword161
      MSSQL_PID: Express
      MSSQL_USER: user
      MSSQL_PASSWORD: password
    ports:
      - "1433:1433"
    volumes:
      - ./.meta/db/data:/var/opt/mssql/data
      - ./.meta/db/log:/var/opt/mssql/log
      - ./.meta/db/secrets:/var/opt/mssql/secrets
