version: "3"
services:
  backend-aspnet:
    image: samarkinivan/messenger-server:latest
    container_name: messenger-server
    restart: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_HOST: database-mssql
    ports:
      - "8080:8080"
    depends_on:
      - database-mssql
      - rabbitmq
      - redis
    volumes:
      - ./.meta/server/uploads:/Messenger.Persistence/Uploads

  database-mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: messenger-database
    restart: on-failure
    user: root
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: SecretPassword161
      MSSQL_PID: Express
      MSSQL_USER: user
      MSSQL_PASSWORD: password
    ports:
      - "1433:1433"
    volumes:
      - ./.meta/mssql/data:/var/opt/mssql/data
      - ./.meta/mssql/log:/var/opt/mssql/log
      - ./.meta/mssql/secrets:/var/opt/mssql/secrets

  rabbitmq:
    image: rabbitmq:latest
    container_name: messenger-rabbit-mq
    restart: on-failure
    ports:
      - 5672:5672

  redis:
    image: redis:latest
    container_name: messenger-redis
    restart: on-failure
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: password
      REDIS_PORT: 6379
      REDIS_DATABASES: 16
    volumes:
      - ./.meta/redis/data:/root/redis
      - ./.meta/redis/conf:/usr/local/etc/redis/redis.conf
