services:
  # chat-service:
  #   image: samarkinivan/chat-service:latest
  #   container_name: chat-service
  #   restart: on-failure
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: Development
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - database-mssql
  #     - rabbitmq
  #     - redis
  #   volumes:
  #     - ./.meta/server/uploads:/Messenger.Persistence/Uploads

  database-mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: chat-service-db
    restart: on-failure
    user: root
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: SecretPassword161
      MSSQL_PID: Express
      MSSQL_USER: user
      MSSQL_PASSWORD: password
    ports:
      - "1433:1433"
    volumes:
      - ./.meta/mssql/data:/var/opt/mssql/data
      - ./.meta/mssql/log:/var/opt/mssql/log
      - ./.meta/mssql/secrets:/var/opt/mssql/secrets

  rabbitmq:
    image: rabbitmq:3-management
    container_name: chat-service-rabbitmq
    hostname: rabbitmq
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - ./.meta/rabbitmq/data/:/var/lib/rabbitmq
      - ./.meta/rabbitmq/log/:/var/log/rabbitmq

  redis:
    image: redis:latest
    container_name: chat-service-redis
    restart: on-failure
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: password
      REDIS_PORT: 6379
      REDIS_DATABASES: 16
    volumes:
      - ./.meta/redis/data:/root/redis
      - ./.meta/redis/conf:/usr/local/etc/redis/redis.conf
