name: CI/CD

on:
  pull_request:
    branches: ["master", "develop"]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
        run: bash ./.github/scripts/exec-build.sh

  publish:
    runs-on: ubuntu-latest
    needs: build

    if: github.event_name == 'release' && github.event.action == 'created'

    steps:
      - uses: actions/checkout@v4
      - name: Publish to docker
        run: bash ./.github/scripts/exec-publish.sh

  deploy:
    runs-on: ubuntu-latest
    needs: publish

    if: github.event_name == 'release' && github.event.action == 'created'

    steps:
      - uses: actions/checkout@v4
      - name: Deploy to prod
        run: bash ./.github/scripts/exec-deploy.sh
