name: CI/CD

on:
  push:
    branches: ["master", "develop"]
    tags:
      - "v*"
  pull_request:
    branches: ["master", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: bash ./.github/scripts/exec-build.sh

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Publish the Docker image
        run: bash ./.github/scripts/exec-publish.sh

  deploy:
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - uses: actions/checkout@v4
      - name: Deploy to prod
        run: bash ./.github/scripts/exec-deploy.sh
